imports:
    - { resource: 'parameters.yml' }
    - { resource: 'security.yml' }

parameters:

    # Locales
    routing_locales: '(fr|en)'
    enabled_locales: ['fr', 'en']

    # Assets
    static_assets_base_path: 'assets' # corresponding to __STATIC_ASSETS_BASE_PATH__ value in webpack.config.js
    uploads_assets_base_path: 'uploads'

    # Application images
    application_images_webroot_relative_dir: '%uploads_assets_base_path%/application_images'
    application_images_dir: '%kernel.project_dir%/web/%application_images_webroot_relative_dir%'

    # API
    build_token_ttl: 600 # seconds

framework:
    translator:
        fallbacks: ['%default_locale%']
    default_locale: '%default_locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%session_save_path%'
    fragments: ~
    http_method_override: true
    assets:
        packages:
            static:
                base_path: '%static_assets_base_path%'
    php_errors:
        log: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        timezone: '%timezone%'
        application_images_webroot_relative_dir: '%application_images_webroot_relative_dir%'

doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: 'UTF8'
        server_version: '%database_server_version%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: 'memory' }

stof_doctrine_extensions:
    default_locale: '%default_locale%'
    orm:
        default:
            timestampable: true

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

bazinga_js_translation:
    active_locales: '%enabled_locales%'
    locale_fallback: '%default_locale%'
