security:
    encoders:
        LinkValue\Appbuild\UserBundle\Entity\User:
           algorithm: 'bcrypt'

    providers:
        db_user_provider:
           entity:
               class: 'AppbuildUserBundle:User'
               property: 'email'

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: '^/(_(profiler|wdt)|assets|uploads)/'
            security: false

        # API security
        public_api:
            pattern:  '^/api/login_check'
            stateless: true
            anonymous: true
            json_login:
                check_path: 'appbuild_api_login_check'
                success_handler: 'lexik_jwt_authentication.handler.authentication_success'
                failure_handler: 'lexik_jwt_authentication.handler.authentication_failure'
                require_previous_session: false

        api:
            pattern: '^/api'
            stateless: true
            guard:
                authenticators:
                    - 'lexik_jwt_authentication.jwt_token_authenticator'

        # js translations bundle route must be accessible without logging in
        js_translations:
            pattern: '^/translations'
            security: false

        # manifest and file downloading must be accessible without logging in
        accessible_files:
            pattern: '^/\w+/application/\d+/build/\d+/(manifest|file)'
            security: false

        # all remaining routes require authentication
        secured_area:
            pattern: '^/'
            anonymous: true
            form_login:
                login_path: 'appbuild_admin_user_login'
                check_path: 'appbuild_user_login_check'
                default_target_path: 'appbuild_admin_application_list'
                always_use_default_target_path: true # otherwise it redirects to an AJAX callback route
            logout:
                path: 'appbuild_user_logout'
                target: 'appbuild_admin_user_login'
            provider: 'db_user_provider'
            remember_me:
                secret: '%secret%'

    role_hierarchy:
        ROLE_ADMIN: ['ROLE_USER']
        ROLE_SUPER_ADMIN: ['ROLE_ADMIN']

    access_control:
        - { path: '/login', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '/register', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/api/login', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/', roles: 'ROLE_USER' }
