---

workspace: '/var/www/Appbuild'

sites:
  - { name: 'Appbuild', server_name: 'local.appbuild.com', template: 'vhost.symfony.j2', client_max_body_size: '1024M' }

mysql:
  users:
    - { name: 'root', password: '' }
  databases:
    - { name: 'appbuild' }

php_versions: ['7.0']
php_upload_max_filesize: '1024M'
php_post_max_size: '1024M'

node_version: '7.x'
